package be.esi.alg2.arbre.gui;

import be.esi.alg2.arbre.seldto.ArbreSel;
import be.esi.alg2.gui.outils.JPCritSelGenerique;

/**
 *
 * @author Florian
 */
public class JPRechercheArbre extends JPCritSelGenerique<ArbreSel> {

    /**
     * Creates new form JPRechercheArbre
     */
    public JPRechercheArbre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        debNom = new javax.swing.JTextField();

        jLabel1.setText("Début du nom :");

        debNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debNomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(debNom, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(debNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void debNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debNomActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField debNom;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setSel(ArbreSel sel) {
        if (sel == null) {
            this.debNom.setText("");
        } else {
            this.debNom.setText(""+sel.getNom());
        }
    }

    @Override
    public ArbreSel getCriteres() {
        ArbreSel aSel = new ArbreSel(this.debNom.getText());
        return aSel;
    }
}
